---
- name: Ensure groups exist
  group:
    name: "{{ item.name }}"
    state: "{% if item.present %}present{% else %}absent{% endif %}"
  with_items: "{{ usergroups }}"

- name: Add users
  user:
    name={{ item.name }}
    system={{ item.sudoer }}
    shell=/bin/bash
    password=$6$rounds=656000$iO7Q9L6/w8dUUQVf$rmtnxrQ15TGAfG5ODxQ/WGyEpTwk.vD1W.UtedmOlo9YNkrIwapYMjmKmteEnUJmRYucgUVxXUQy7gtenpLmw0
    update_password=on_create
  register: result
  with_items: "{{ users }}"

- name: Expire password of created users
  command: "chage -d 0 {{ item.name }}"
  when: item.changed == true
  with_items: "{{ result.results }}"

- name: Add users to their groups
  user:
    name={{ item.name }}
    append=yes
    groups={{ item.group }}
  when: item.group is defined
  with_items: "{{ users }}"

- name: Insert public keys for ssh
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "https://github.com/{{ item.ghandle | default(item.name) }}.keys"
  with_items: "{{ users }}"
